---
name: Benchmarking hash functions

on:
  push:
    branches:
      - feature/introduce-pyperf
  workflow_dispatch:

permissions: {}

jobs:
  benchmark:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # pandas 2.0.3 does not provide wheels for Python 3.12
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install ".[dev]"
          pip uninstall pyperf | yes
      - name: Tune pyperf
        run: |
          sudo modprobe msr
          lscpu -a -e
          lsmod | grep msr
          sudo python -m pip install pyperf
          sudo python -m pyperf system tune
      - name: Benchmark hash functions
        run: python becnhmark/bechmark.py
