# This workflow is intended for quick building tests.
# Use wheels.yml for complete building/uploading tests.
name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pytest
        pip install numpy
        pip install .
    - name: Test with pytest
      run: python -m pytest
