---
name: Build and Upload Wheels to TestPyPI

on:
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/wheels.yml
    with:
      pypi-repository: "testpypi"
    secrets:
      pypi-username: ${{ secrets.TEST_PYPI_USERNAME }}
      pypi-password: ${{ secrets.TEST_PYPI_PASSWORD }}
